Repository ros2/ros2cli, pull requests merged in 2018-06, with the labels that each got.

#93 ignore F841 from latest Pyflakes release
  ros2cli/ros2cli/entry_points.py
  ros2cli/ros2cli/plugin_system.py
  ros2service/ros2service/verb/call.py
  ros2topic/ros2topic/verb/pub.py
Labels: in review

#95 add ros2 param
  ros2param/package.xml
  ros2param/ros2param/__init__.py
  ros2param/ros2param/api/__init__.py
  ros2param/ros2param/command/__init__.py
  ros2param/ros2param/command/param.py
  ros2param/ros2param/verb/__init__.py
  ros2param/ros2param/verb/delete.py
  ros2param/ros2param/verb/get.py
  ros2param/ros2param/verb/list.py
  ros2param/ros2param/verb/set.py
  ros2param/setup.py
  ros2param/test/test_copyright.py
  ros2param/test/test_flake8.py
  ros2param/test/test_pep257.py
Labels: enhancement, in review

#96 Implementation for #89
  ros2pkg/ros2pkg/verb/prefix.py
Labels: enhancement, in review

#97 add ros2 lifecycle
  ros2lifecycle/package.xml
  ros2lifecycle/ros2lifecycle/__init__.py
  ros2lifecycle/ros2lifecycle/api/__init__.py
  ros2lifecycle/ros2lifecycle/command/__init__.py
  ros2lifecycle/ros2lifecycle/command/lifecycle.py
  ros2lifecycle/ros2lifecycle/verb/__init__.py
  ros2lifecycle/ros2lifecycle/verb/get.py
  ros2lifecycle/ros2lifecycle/verb/list.py
  ros2lifecycle/ros2lifecycle/verb/set.py
  ros2lifecycle/setup.py
  ros2lifecycle/test/test_copyright.py
  ros2lifecycle/test/test_flake8.py
  ros2lifecycle/test/test_pep257.py
Labels: enhancement, in review

#98 update ros2 param list output for a specific node
  ros2param/ros2param/verb/list.py
Labels: enhancement, in review

#99 add missing arg to ros2 service list
  ros2service/ros2service/verb/list.py
Labels: bug, in review

#101 add colcon.pkg file to source completion scripts
  ros2cli/colcon.pkg
Labels: bug, in review

#103 ros2lifecycle: fix dep and import
  ros2lifecycle/package.xml
  ros2lifecycle/ros2lifecycle/verb/set.py
Labels: bug, in review

#102 use (bash)compinit for zsh completion
  ros2cli/completion/ros2-argcomplete.zsh
Labels: bug, in review

#104 Specific message when unset parameters are retrieved
  ros2param/ros2param/verb/get.py
Labels: in review

#111 ros2pkg: avoid requiring git
  ros2pkg/ros2pkg/verb/create.py
Labels: bug, in review

#115 cancel timer before letting caller use the node to avoid spurious wakeups for consumers
  ros2cli/ros2cli/node/direct.py
Labels: in review

#116 pass actual node object to subscriber function
  ros2topic/ros2topic/verb/echo.py
Labels: in review

#113 hide window of spawned daemon
  ros2cli/ros2cli/node/daemon.py
Labels: bug, in review

#118 fix tests to use packages which register themselves at the index
  ros2msg/package.xml
  ros2msg/test/test_api.py
  ros2pkg/test/test_api.py
  ros2pkg/test/test_cli.py
  ros2srv/package.xml
  ros2srv/test/test_api.py
Labels: bug, in review
