Repository ros2/ros2cli, pull requests merged in 2019-07, with the labels that each got.

#291 fix rename package-format to match other flags (#290)
  ros2pkg/ros2pkg/verb/create.py
Labels: in review

#216 Add no_str and no_arr options for ros2 topic echo
  ros2topic/ros2topic/verb/echo.py
Labels: in review

#287 Added tests for ros2action and ros2msg
  test_ros2cli/CMakeLists.txt
  test_ros2cli/package.xml
  test_ros2cli/test/config_ros2action_test.py
  test_ros2cli/test/config_ros2msg_test.py
  test_ros2cli/test/test_config.py
  test_ros2cli/test/test_process_output_customizable.py.in
Labels: enhancement, in review

#285 Add param dump <node-name>
  ros2param/ros2param/api/__init__.py
  ros2param/ros2param/verb/dump.py
  ros2param/setup.py
  ros2param/test/test_verb_dump.py
Labels: in review

#306 Fix ros2 topic bw output units.
  ros2topic/ros2topic/verb/bw.py
Labels: enhancement

#305 Alphasort ros2 node list output.
  ros2node/ros2node/verb/list.py
Labels: enhancement
