Repository ros2/ros2cli, pull requests merged in 2019-03, with the labels that each got.

#205 update logger.warn (deprecated) to logger.warning
  ros2cli/ros2cli/entry_points.py
  ros2cli/ros2cli/plugin_system.py
Labels: in review

#208 ros2lifecycle `nodes` and `get` verbs, now showing hidden nodes when requested
  ros2lifecycle/ros2lifecycle/api/__init__.py
Labels: in progress

#206 Solved bug when trying to find node info in namespaces
  ros2node/ros2node/api/__init__.py
  ros2node/ros2node/verb/info.py
  ros2node/test/test_node.py
Labels: in progress

#210 add section about DCO to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in review

#211 support array.array and numpy.ndarray field types
  ros2topic/package.xml
  ros2topic/ros2topic/verb/echo.py
Labels: enhancement, in review

#212 use yaml.safe_load instead of deprecated yaml.load
  ros2service/ros2service/verb/call.py
  ros2topic/ros2topic/verb/pub.py
Labels: in review
