Repository ros2/ros2cli, pull requests merged in 2019-10, with the labels that each got.

#341 ros2doctor: add topic check
  ros2doctor/ros2doctor/api/topic.py
  ros2doctor/setup.py
  ros2doctor/test/test_topic.py
Labels: in review

#345 ros2node info: add action category
  ros2node/ros2node/api/__init__.py
  ros2node/ros2node/verb/info.py
Labels: in review

#352 Fix multicast entrypoint
  ros2multicast/setup.py
Labels: bug

#353 fix sourcing completion scripts in Debian package
  ros2cli/resource/local_setup.bash
  ros2cli/resource/local_setup.zsh
  ros2cli/resource/package.dsv
  ros2cli/setup.py
Labels: bug, in review

#364 add completion for parameter name arguments
  ros2param/ros2param/api/__init__.py
  ros2param/ros2param/verb/delete.py
  ros2param/ros2param/verb/get.py
  ros2param/ros2param/verb/set.py
Labels: enhancement, in review

#365 Backport creating ament python packages to dashing
  ros2pkg/ros2pkg/api/create.py
  ros2pkg/ros2pkg/resource/ament_python/init.py.em
  ros2pkg/ros2pkg/resource/ament_python/main.py.em
  ros2pkg/ros2pkg/resource/ament_python/resource_file.em
  ros2pkg/ros2pkg/resource/ament_python/setup.cfg.em
  ros2pkg/ros2pkg/resource/ament_python/setup.py.em
  ros2pkg/ros2pkg/resource/ament_python/test_copyright.py.em
  ros2pkg/ros2pkg/resource/ament_python/test_flake8.py.em
  ros2pkg/ros2pkg/resource/ament_python/test_pep257.py.em
  ros2pkg/ros2pkg/verb/create.py
Labels: in review

#367 add ros2 param describe
  ros2param/ros2param/api/__init__.py
  ros2param/ros2param/verb/describe.py
  ros2param/setup.py
Labels: enhancement, in review

#368 ensure ros2 interface show has trailing newline
  ros2action/ros2action/verb/show.py
  ros2interface/ros2interface/verb/show.py
  ros2msg/ros2msg/verb/show.py
  ros2srv/ros2srv/verb/show.py
Labels: in review

#284 Make daemon “reset” itself when the IP address changes
  ros2cli/package.xml
  ros2cli/ros2cli/daemon/__init__.py
  ros2cli/ros2cli/node/daemon.py
  ros2cli/ros2cli/verb/daemon/start.py
Labels: enhancement, in review

#370 Fix NetworkCheck AttributeError
  ros2doctor/ros2doctor/api/network.py
Labels: in review

#363 Deprecate ros2msg and ros2srv
  ros2msg/package.xml
  ros2msg/ros2msg/verb/list.py
  ros2msg/ros2msg/verb/package.py
  ros2msg/ros2msg/verb/packages.py
  ros2msg/ros2msg/verb/show.py
  ros2srv/package.xml
  ros2srv/ros2srv/verb/list.py
  ros2srv/ros2srv/verb/package.py
  ros2srv/ros2srv/verb/packages.py
  ros2srv/ros2srv/verb/show.py
Labels: in review

#373 [ros2node] Add option to info verb to display hidden names
  ros2component/ros2component/api/__init__.py
  ros2node/ros2node/api/__init__.py
  ros2node/ros2node/verb/info.py
Labels: enhancement, in review

#386 [ros2interface] Fix tests
  ros2interface/test/test_cli.py
Labels: in review
