Repository ros2/ros2cli, pull requests merged in 2019-12, with the labels that each got.

#405 [ros2action] Remove show verb
  ros2action/ros2action/api/__init__.py
  ros2action/ros2action/verb/show.py
  ros2action/setup.py
  ros2action/test/test_api.py
  ros2action/test/test_cli.py
Labels: in review

#413 [eloquent] [ros2action] Deprecate show verb
  ros2action/ros2action/verb/show.py
  ros2action/test/test_cli.py
Labels: enhancement

#416 Add timestamp to ros2topic test where needed
  ros2topic/test/test_cli.py
Labels: in review

#418 partially revert [dashing backport] add service clients to ros2node info
  ros2node/ros2node/api/__init__.py
  ros2node/ros2node/verb/info.py
Labels: bug, in review

#407 Remove ros2msg and ros2srv
  ros2msg/package.xml
  ros2msg/resource/ros2msg
  ros2msg/ros2msg/__init__.py
  ros2msg/ros2msg/api/__init__.py
  ros2msg/ros2msg/command/__init__.py
  ros2msg/ros2msg/command/msg.py
  ros2msg/ros2msg/verb/__init__.py
  ros2msg/ros2msg/verb/list.py
  ros2msg/ros2msg/verb/package.py
  ros2msg/ros2msg/verb/packages.py
  ros2msg/ros2msg/verb/show.py
  ros2msg/setup.py
  ros2msg/test/test_api.py
  ros2msg/test/test_cli.py
  ros2msg/test/test_copyright.py
  ros2msg/test/test_flake8.py
  ros2msg/test/test_pep257.py
  ros2msg/test/test_xmllint.py
  ros2srv/package.xml
  ros2srv/resource/ros2srv
  ros2srv/ros2srv/__init__.py
  ros2srv/ros2srv/api/__init__.py
  ros2srv/ros2srv/command/__init__.py
  ros2srv/ros2srv/command/srv.py
  ros2srv/ros2srv/verb/__init__.py
  ros2srv/ros2srv/verb/list.py
  ros2srv/ros2srv/verb/package.py
  ros2srv/ros2srv/verb/packages.py
  ros2srv/ros2srv/verb/show.py
  ros2srv/setup.py
  ros2srv/test/test_api.py
  ros2srv/test/test_cli.py
  ros2srv/test/test_copyright.py
  ros2srv/test/test_flake8.py
  ros2srv/test/test_pep257.py
  ros2srv/test/test_xmllint.py
Labels: in review

#388 [ros2doctor] Check for deprecated packages
  ros2doctor/package.xml
  ros2doctor/ros2doctor/api/package.py
  ros2doctor/setup.py
Labels: in review

#406 [ros2action] Refactor send_goal implementation
  ros2action/ros2action/verb/send_goal.py
Labels: enhancement, in review

#422 Use imperative mood in constructor docstring.
  ros2topic/test/qos_subscription.py
Labels: in review

#415 [ros2topic] Use import message logic provided by rosidl_runtime_py
  ros2topic/ros2topic/api/__init__.py
  ros2topic/ros2topic/verb/echo.py
  ros2topic/ros2topic/verb/pub.py
  ros2topic/test/fixtures/repeater_node.py
Labels: enhancement, in review

#423 Able to show info of hidden topic.
  ros2topic/ros2topic/verb/info.py
Labels: enhancement
