Repository ros2/ros2cli, pull requests merged in 2019-05, with the labels that each got.

#227 fix name of standalone verb
  ros2component/ros2component/verb/standalone.py
Labels: in review

#229 use yaml.safe_load (round2)
  ros2action/ros2action/verb/send_goal.py
  ros2param/ros2param/api/__init__.py
Labels: in review

#228 Remove unused test dependency
  ros2topic/package.xml
Labels: in review

#232 add xmllint linter test
  ros2action/package.xml
  ros2action/test/test_xmllint.py
  ros2cli/package.xml
  ros2cli/test/test_xmllint.py
  ros2component/package.xml
  ros2component/test/test_xmllint.py
  ros2lifecycle/package.xml
  ros2lifecycle/test/test_xmllint.py
  ros2msg/package.xml
  ros2msg/test/test_xmllint.py
  ros2multicast/package.xml
  ros2multicast/test/test_xmllint.py
  ros2node/package.xml
  ros2node/test/test_xmllint.py
  ros2param/package.xml
  ros2param/test/test_xmllint.py
  ros2pkg/package.xml
  ros2pkg/test/test_xmllint.py
  ros2run/package.xml
  ros2run/test/test_xmllint.py
  ros2service/package.xml
  ros2service/test/test_xmllint.py
  ros2srv/package.xml
  ros2srv/test/test_xmllint.py
  ros2topic/package.xml
  ros2topic/test/test_xmllint.py
Labels: in review

#230 separate the yaml of messages with three dashes
  ros2topic/ros2topic/verb/echo.py
Labels: enhancement, in review

#234 Fix deprecation warnings
  ros2topic/ros2topic/verb/bw.py
  ros2topic/ros2topic/verb/delay.py
  ros2topic/ros2topic/verb/echo.py
  ros2topic/ros2topic/verb/hz.py
  ros2topic/ros2topic/verb/pub.py
Labels: in progress

#237 [ros2topic] Handle multiple namespace parts in message type
  ros2topic/ros2topic/api/__init__.py
Labels: in review

#239 Add support for creating a package with format 3
  ros2pkg/ros2pkg/api/create.py
  ros2pkg/ros2pkg/resource/package_environment/package.xml.em
  ros2pkg/ros2pkg/verb/create.py
Labels: in review

#238 [ros2topic] Update pub to use qos command line settings.
  ros2topic/ros2topic/api/__init__.py
  ros2topic/ros2topic/verb/pub.py
  ros2topic/test/qos_subscription.py
Labels: in review

#241 use new type identification for lifecycle nodes
  ros2lifecycle/ros2lifecycle/api/__init__.py
Labels: bug, in review

#242 use new type identification for service calls
  ros2service/ros2service/verb/call.py
Labels: bug, in review

#243 fix sourcing argcomplete script in zsh
  ros2cli/resource/local_setup.zsh
Labels: bug, in review

#247 add support for service type name without 'srv' namespace part
  ros2service/ros2service/verb/call.py
Labels: enhancement, in review

#249 fix service names to contain 'srv' namespace part
  ros2component/ros2component/api/__init__.py
Labels: bug, in review

#251 don't start parameter service in daemon
  ros2cli/ros2cli/daemon/__init__.py
  ros2cli/ros2cli/node/direct.py
Labels: bug, in review

#252 only allow window sizes of 1 and higher
  ros2topic/ros2topic/verb/bw.py
  ros2topic/ros2topic/verb/delay.py
  ros2topic/ros2topic/verb/hz.py
Labels: bug, in review

#253 update help of --spin-time
  ros2cli/ros2cli/node/direct.py
Labels: documentation, in review

#254 reset goal_handle to avoid attempt to cancel
  ros2action/ros2action/verb/send_goal.py
Labels: bug, in review

#259 use three-part interface names in msg/srv/action show and msg/srv/ list
  ros2action/ros2action/api/__init__.py
  ros2action/ros2action/verb/show.py
  ros2msg/ros2msg/api/__init__.py
  ros2msg/ros2msg/verb/list.py
  ros2msg/ros2msg/verb/show.py
  ros2srv/ros2srv/api/__init__.py
  ros2srv/ros2srv/verb/list.py
  ros2srv/ros2srv/verb/show.py
Labels: bug, in review

#258 abort pkg create if destination directory exists
  ros2pkg/ros2pkg/verb/create.py
Labels: bug, in review

#263 fix message/service naming in package verbs
  ros2msg/ros2msg/verb/package.py
  ros2srv/ros2srv/verb/package.py
Labels: in review

#265 fix param list for nodes which don't have the service
  ros2param/package.xml
  ros2param/ros2param/verb/list.py
Labels: bug, in review

#268 fix param list for hidden nodes
  ros2param/ros2param/verb/list.py
Labels: bug, in review
