Repository ros2/ros2cli, pull requests merged in 2019-11, with the labels that each got.

#384 Fix ros2topic test_echo_pub.py test suite
  ros2topic/test/test_echo_pub.py
Labels: in review

#398 Fix ros2 topic pub --node-name
  ros2cli/ros2cli/node/direct.py
  ros2topic/ros2topic/verb/pub.py
Labels: bug, in review

#400 [ros2topic] show default values for --qos-* options
  ros2topic/ros2topic/api/__init__.py
Labels: enhancement, in review

#404 Update network check to fix missing flags on Windows
  ros2doctor/ros2doctor/api/network.py
Labels: in review

#409 [dashing backport] add service clients to ros2node info
  ros2node/ros2node/api/__init__.py
  ros2node/ros2node/verb/info.py
Labels: in review
