Repository ros2/ros2cli, pull requests merged in 2019-06, with the labels that each got.

#272 add 'topic type' verb
  ros2topic/ros2topic/verb/type.py
  ros2topic/setup.py
Labels: enhancement

#274 add 'service find' verb
  ros2service/ros2service/verb/find.py
  ros2service/setup.py
Labels: enhancement

#280 Add pkg xml verb
  ros2pkg/ros2pkg/verb/xml.py
  ros2pkg/setup.py
Labels: enhancement, in progress

#282 add --ttl option to multicast send
  ros2multicast/ros2multicast/api/__init__.py
  ros2multicast/ros2multicast/verb/send.py
Labels: enhancement, in review
