Repository ros2/ros2cli, pull requests merged in 2020-01, with the labels that each got.

#434 Add docblock for ros2interface command
  ros2interface/ros2interface/command/interface.py
Labels: enhancement

#436 only load required entry points which improves the performance
  ros2action/ros2action/command/action.py
  ros2cli/ros2cli/cli.py
  ros2cli/ros2cli/command/__init__.py
  ros2cli/ros2cli/command/daemon.py
  ros2cli/ros2cli/entry_points.py
  ros2cli/ros2cli/plugin_system.py
  ros2component/ros2component/command/component.py
  ros2interface/ros2interface/command/interface.py
  ros2lifecycle/ros2lifecycle/command/lifecycle.py
  ros2multicast/ros2multicast/command/multicast.py
  ros2node/ros2node/command/node.py
  ros2param/ros2param/command/param.py
  ros2pkg/ros2pkg/command/pkg.py
  ros2service/ros2service/command/service.py
  ros2topic/ros2topic/command/topic.py
Labels: enhancement, in review

#437 pass argv to CommandExtension.add_arguments if available
  ros2cli/ros2cli/command/__init__.py
Labels: bug, in review

#438 fix linter warning about bad quotes
  ros2cli/ros2cli/command/__init__.py
Labels: bug, in review

#441 fix ros2param tests
  ros2param/ros2param/command/param.py
Labels: bug

#446 override parse_known_args for completion to work with partial argparse tree
  ros2cli/ros2cli/command/__init__.py
Labels: bug
