Repository ros2/ros2cli, pull requests merged in 2020-05, with the labels that each got.

#508 Avoid array.array in ros2 param output.
  ros2param/ros2param/api/__init__.py
  ros2param/test/fixtures/parameter_node.py
  ros2param/test/test_verb_dump.py
Labels: enhancement

#510 Fix typo in `ros2 topic delay` help
  ros2topic/ros2topic/verb/delay.py
Labels: documentation

#513 Ensure ros2doctor ROS nodes have valid names.
  ros2doctor/ros2doctor/verb/hello.py
  ros2doctor/test/test_api.py
  ros2doctor/test/test_cli.py
Labels: bug

#516 [ros2interface] Remove usage of deprecated std_msgs and std_srvs packages
  ros2interface/package.xml
  ros2interface/ros2interface/verb/package.py
  ros2interface/ros2interface/verb/proto.py
  ros2interface/ros2interface/verb/show.py
  ros2interface/test/test_cli.py
Labels: bug

#387 [ros2interface] Allow stdin input for 'ros2 interface show'
  ros2interface/ros2interface/verb/show.py
  ros2interface/test/test_cli.py
Labels: enhancement, in review
