Repository ros2/ros2cli, pull requests merged in 2020-02, with the labels that each got.

#445 [ros2doctor] Improve doctor_warn()
  ros2doctor/ros2doctor/api/__init__.py
  ros2doctor/ros2doctor/api/format.py
  ros2doctor/ros2doctor/api/network.py
  ros2doctor/ros2doctor/api/package.py
  ros2doctor/ros2doctor/api/platform.py
  ros2doctor/ros2doctor/api/topic.py
  ros2doctor/ros2doctor/command/doctor.py
Labels: in review

#452 [ros2doctor] Handle non-metapackages in rosdistro check
  ros2doctor/ros2doctor/api/package.py
Labels: bug

#459 Add delay when retrying tests involving the CLI daemon
  ros2action/test/test_cli.py
  ros2lifecycle/test/test_cli.py
  ros2node/test/test_cli.py
  ros2service/test/test_cli.py
  ros2topic/test/test_cli.py
Labels: enhancement
