Repository ros2/ros2cli, pull requests merged in 2021-04, with the labels that each got.

#351 Add verbose info for topic list
  ros2topic/ros2topic/verb/list.py
  ros2topic/test/test_cli.py
Labels: enhancement, in progress, requires-changes

#627 [ros2pkg] Use underscores in setup.cfg.em instead of dashes
  ros2pkg/ros2pkg/resource/ament_python/setup.cfg.em
Labels: bug

#621 [ros2doctor] Add QoS compatibility check and report
  ros2doctor/ros2doctor/api/__init__.py
  ros2doctor/ros2doctor/api/qos_compatibility.py
  ros2doctor/ros2doctor/api/topic.py
  ros2doctor/setup.py
  ros2doctor/test/fixtures/listener_node_with_reliable_qos.py
  ros2doctor/test/fixtures/talker_node_with_best_effort_qos.py
  ros2doctor/test/fixtures/talker_node_with_reliable_qos.py
  ros2doctor/test/test_qos_compatibility.py
Labels: enhancement
